# Generated by Django 4.2.4 on 2024-05-26 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('order_id', models.CharField(default=orders.models.generate_order_id, max_length=14, primary_key=True, serialize=False)),
                ('printer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be a 10 digit number without leading zeros', regex='^[1-9][0-9]{9}$')])),
                ('quantity', models.IntegerField(default=0)),
                ('front_side_image', models.ImageField(upload_to='order_images')),
                ('back_side_image', models.ImageField(blank=True, null=True, upload_to='order_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
